# add a label to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
label_prs: update

# assign users to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
assignees:
 - jkvakaric

# Specify requirement files by hand, default is empty
# default: empty
# allowed: list
requirements:
  - requirements/base.txt
  - requirements/local.txt
  - requirements/production.txt
  - Pipfile
