# Generated by Django 2.0.5 on 2018-05-23 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='event name')),
                ('event_start', models.DateTimeField(verbose_name='event start datetime')),
                ('event_end', models.DateTimeField(verbose_name='event end datetime')),
            ],
        ),
        migrations.CreateModel(
            name='DonationInvite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_invite', to='administration.DonationEvent', verbose_name='donation event')),
            ],
        ),
        migrations.CreateModel(
            name='DonationVenue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='donation venue name')),
                ('address', models.CharField(max_length=255, verbose_name='donation venue address')),
                ('average_recall', models.FloatField(verbose_name='average recall percentage')),
            ],
        ),
        migrations.AddField(
            model_name='donationevent',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_event', to='administration.DonationVenue', verbose_name='donation venue'),
        ),
    ]
