# Generated by Django 2.0.5 on 2018-05-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationvenue',
            name='average_recall',
            field=models.FloatField(default=1.0, verbose_name='average recall percentage'),
        ),
    ]
