# Generated by Django 2.0.5 on 2018-05-24 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0002_default_recall'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationinvite',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='invitation is confirmed'),
        ),
        migrations.AddField(
            model_name='donationinvite',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_invites', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='donationevent',
            name='event_end',
            field=models.CharField(max_length=255, verbose_name='event end date and time'),
        ),
        migrations.AlterField(
            model_name='donationevent',
            name='event_start',
            field=models.CharField(max_length=255, verbose_name='event start date and time'),
        ),
    ]
