# Generated by Django 2.0.5 on 2018-05-24 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0003_invites'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedDonation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cd_event', to='administration.DonationEvent', verbose_name='donation event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_donations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
