# Generated by Django 2.0.5 on 2018-05-23 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100, verbose_name='text')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False, verbose_name='is seen')),
                ('link', models.CharField(default='dashboard', max_length=100, verbose_name='link')),
                ('faicon', models.CharField(default='warning', max_length=20, verbose_name='fa icon')),
                ('color', models.CharField(default='yellow', max_length=20, verbose_name='color')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='the user notification is assigned to')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
